config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :items  do
    resources :orders, only: [:create, :index]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item

  def create
    like = current_user.likes.build(item_id: params[:item_id])
    like.save

    respond_to do |format|
      format.js
    end
  end

  def destroy
    like = Like.find_by(params[:item_id])
    like.destroy
    respond_to do |format|
      format.js
    end

  end

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
      <% if user_signed_in? && @item.liked_by?(current_user)%>
      <%= image_tag "hoshi.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
       <%=link_to "お気に入り", item_like_path(@item.id),  data: { turbo_method: :delete }, remote: true %>
      <% else %>
      <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
       <%=link_to "お気に入り", item_likes_path(@item.id), data: { turbo_method: :post }, remote: true %>
       <% end %>

app/views/likes/create.js.erb
$('like-btn<%= @item.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {item: @item}) %>"

app/views/likes/destroy.js.erb
document.getElementById('like-btn<%= @item.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {item: @item}) %>"